# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v3/mobilegwsvc/commonmodels/hub/device/light/properties/eol_sensor_properties.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'v3/mobilegwsvc/commonmodels/hub/device/light/properties/eol_sensor_properties.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nSv3/mobilegwsvc/commonmodels/hub/device/light/properties/eol_sensor_properties.proto\x12Rsystems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.hub.device.light.properties\"\xa8\x08\n\x13\x45olSensorProperties\x12\x86\x01\n\x0b\x65ol_sensors\x18\x01 \x03(\x0b\x32q.systems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.hub.device.light.properties.EolSensorProperties.EolSensor\x1a\xb8\x01\n\tEolSensor\x12\x92\x01\n\x11\x63ustom_alarm_type\x18\x01 \x01(\x0e\x32w.systems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.hub.device.light.properties.EolSensorProperties.CustomAlarmType\x12\x16\n\x0eis_main_sensor\x18\x02 \x01(\x08\"\xcc\x05\n\x0f\x43ustomAlarmType\x12!\n\x1d\x43USTOM_ALARM_TYPE_UNSPECIFIED\x10\x00\x12\x1f\n\x1b\x43USTOM_ALARM_TYPE_INTRUSION\x10\x01\x12\x1a\n\x16\x43USTOM_ALARM_TYPE_FIRE\x10\x02\x12\x1d\n\x19\x43USTOM_ALARM_TYPE_MEDICAL\x10\x03\x12\x1b\n\x17\x43USTOM_ALARM_TYPE_PANIC\x10\x04\x12\x19\n\x15\x43USTOM_ALARM_TYPE_GAS\x10\x05\x12\x1c\n\x18\x43USTOM_ALARM_TYPE_TAMPER\x10\x06\x12!\n\x1d\x43USTOM_ALARM_TYPE_MALFUNCTION\x10\x07\x12\x1a\n\x16\x43USTOM_ALARM_TYPE_LEAK\x10\x08\x12\x1d\n\x19\x43USTOM_ALARM_TYPE_SERVICE\x10\t\x12\x1d\n\x19\x43USTOM_ALARM_TYPE_KEY_ARM\x10\n\x12!\n\x1d\x43USTOM_ALARM_TYPE_GLASS_BREAK\x10\x0b\x12&\n\"CUSTOM_ALARM_TYPE_HIGH_TEMPERATURE\x10\x0c\x12%\n!CUSTOM_ALARM_TYPE_LOW_TEMPERATURE\x10\r\x12\x1d\n\x19\x43USTOM_ALARM_TYPE_MASKING\x10\x0e\x12!\n\x1d\x43USTOM_ALARM_TYPE_DURESS_CODE\x10\x0f\x12\x1f\n\x1b\x43USTOM_ALARM_TYPE_VIBRATION\x10\x10\x12&\n\"CUSTOM_ALARM_TYPE_BLOCKING_ELEMENT\x10\x11\x12\"\n\x1e\x43USTOM_ALARM_TYPE_BOLT_CONTACT\x10\x12\x12$\n CUSTOM_ALARM_TYPE_ROLLER_SHUTTER\x10\x13\x12 \n\x1c\x43USTOM_ALARM_TYPE_EVACUATION\x10\x14\x42Y\nRsystems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.hub.device.light.propertiesP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v3.mobilegwsvc.commonmodels.hub.device.light.properties.eol_sensor_properties_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\nRsystems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.hub.device.light.propertiesP\001\272\002\000'
  _globals['_EOLSENSORPROPERTIES']._serialized_start=172
  _globals['_EOLSENSORPROPERTIES']._serialized_end=1236
  _globals['_EOLSENSORPROPERTIES_EOLSENSOR']._serialized_start=333
  _globals['_EOLSENSORPROPERTIES_EOLSENSOR']._serialized_end=517
  _globals['_EOLSENSORPROPERTIES_CUSTOMALARMTYPE']._serialized_start=520
  _globals['_EOLSENSORPROPERTIES_CUSTOMALARMTYPE']._serialized_end=1236
# @@protoc_insertion_point(module_scope)
